version: '3.8'
services:
  php:
    image: yiisoftware/yii2-php:8.2-apache
    restart: always
    volumes:
      - ~/.composer-docker/cache:/root/.composer/cache:delegated
      - ./:/app:delegated
    ports:
      - '8000:80'

  mysql:
    image: mysql:latest
    restart: always
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    volumes:
      - './docker/production/db/initdb.d:/docker-entrypoint-initdb.d'
      - 'db:/var/lib/mysql'
    ports:
      - '6033:3306'

volumes:
  db: { }